IF EXISTS (
    SELECT name
    FROM sys.databases
    WHERE name = N'SDA'
        AND state = 0
)
BEGIN
    ALTER DATABASE SDA SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE SDA;
END

CREATE DATABASE SDA;


